name: crates

on:
    push:
        tags:
            - "*"

jobs:
    publish:
        runs-on: [self-hosted, linux]
        steps:
            - uses: actions/checkout@v2

            - name: setup node
              uses: actions/setup-node@v2
              with:
                  node-version: "14.x"
                  registry-url: "https://registry.npmjs.org"
                  always-auth: true

            - name: setup java
              uses: actions/setup-java@v2
              with:
                  distribution: 'zulu'
                  java-version: '11'

            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable  

            - name: Run openapi-generator
              run: |
                npx @openapitools/openapi-generator-cli generate \
                  --generator-name rust \
                  --config rust-openapi-config.json \
                  --input-spec api.yaml \
                  --output client

            - name: Overwrite Cargo.toml
              run: mv Cargo.toml client/Cargo.toml

            - run: cargo publish --token ${{ secrets.CARGO_AUTH_TOKEN }}
              working-directory: client